# Generated by Django 5.2.16 on 2026-07-21 10:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('state', models.CharField(choices=[('open', 'В работе'), ('submitted', 'Отправлено'), ('released', 'Освобождено')], default='open', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='StoryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Основная User Story', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stories.claim')),
            ],
        ),
        migrations.CreateModel(
            name='DraftResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, choices=[('ok', 'ОК'), ('not_ok', 'НЕ ОК'), ('skip', 'Пропустить')], max_length=10)),
                ('note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='stories.claimitem')),
            ],
        ),
        migrations.AddField(
            model_name='claim',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='stories.participant'),
        ),
        migrations.CreateModel(
            name='RunNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_node_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('code', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=300)),
                ('kind', models.CharField(choices=[('group', 'Раздел'), ('check', 'Проверяемый пункт')], max_length=10)),
                ('position', models.PositiveIntegerField(default=0)),
                ('result_status', models.CharField(blank=True, choices=[('ok', 'ОК'), ('not_ok', 'НЕ ОК')], max_length=10, null=True)),
                ('note', models.TextField(blank=True)),
                ('completed_by_name', models.CharField(blank=True, max_length=80)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='stories.runnode')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='claimitem',
            name='node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='claim_item', to='stories.runnode'),
        ),
        migrations.CreateModel(
            name='SkipEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=80)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skip_events', to='stories.runnode')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StoryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('os', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=10)),
                ('version', models.CharField(max_length=64)),
                ('build', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('active', 'Активен'), ('completed', 'Завершён')], default='active', max_length=12)),
                ('final_status', models.CharField(blank=True, choices=[('ok', 'ОК'), ('not_ok', 'НЕ ОК')], max_length=10, null=True)),
                ('forced', models.BooleanField(default=False)),
                ('template_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-completed_at', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state', 'active')), fields=('os',), name='one_active_run_per_os')],
            },
        ),
        migrations.AddField(
            model_name='runnode',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='stories.storyrun'),
        ),
        migrations.AddField(
            model_name='claim',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='stories.storyrun'),
        ),
        migrations.CreateModel(
            name='TemplateNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=300)),
                ('kind', models.CharField(choices=[('group', 'Раздел'), ('check', 'Проверяемый пункт')], max_length=10)),
                ('position', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='stories.templatenode')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='stories.storytemplate')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='runnode',
            constraint=models.UniqueConstraint(fields=('run', 'code'), name='unique_run_node_code'),
        ),
        migrations.AddConstraint(
            model_name='templatenode',
            constraint=models.UniqueConstraint(fields=('template', 'code'), name='unique_template_node_code'),
        ),
    ]
