# Generated by Django 5.2.16 on 2026-08-03 13:36

from django.db import migrations, models


def mark_existing_current_skips(apps, schema_editor):
    RunNode = apps.get_model("stories", "RunNode")
    skipped_ids = (
        RunNode.objects.filter(
            result_status__isnull=True,
            skip_events__isnull=False,
            claim_item__isnull=True,
        )
        .values_list("id", flat=True)
        .distinct()
    )
    RunNode.objects.filter(id__in=skipped_ids).update(is_skipped=True)


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_seed_initial_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='runnode',
            name='is_skipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storyrun',
            name='final_comment',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(mark_existing_current_skips, migrations.RunPython.noop),
    ]
